# Generated by Django 4.2.11 on 2024-05-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("own_corp", "Can access own corp compliance"),
                    ("any_corp", "Can access any corp compliance"),
                    ("alliance", "Can access alliance compliance"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
